# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
development:
  FB_ID: "1519387744758372"
  FB_SECRET: "ce7f92345cc4b45ee477d84d8c05d0c3"
  STRIPE_PUBLISHABLE_KEY: "pk_test_6LOwWXQ2TMWpKQop2zmuDdiH"
  STRIPE_SECRET_KEY: "sk_test_Jce80QbHktdVz9mrK4Y8EtVj"
  GOOGLE_API_BROWSER_KEY: "AIzaSyBFcIUeA_y8U8yTG56W61vurKHwWi4jTE8"
#  GOOGLE_API_KEY: "AIzaSyDANjx3bosEtIyzJaoWs50Wnt6nt_1rmxU" # "AIzaSyDfmDHVOytPDrRB5C3EdaaIVgK0km5wcQM"


production:
  FB_ID: "1519387221425091"
  FB_SECRET: "ebf6f25e50bd3eb7955f446f6b3d3c6a"
  GOOGLE_API_BROWSER_KEY: "AIzaSyBFcIUeA_y8U8yTG56W61vurKHwWi4jTE8"

#AIzaSyCucfQMKhItzVNiJnxuLkIeQWM5y9VisYQ
CLOUDINARY_URL: "cloudinary://777589833434932:KgdeJHLI2D-5EmNiS18JN5BpKmU@dc2fg86gy"



